global using Microsoft.AspNetCore.Components;
global using System.Web;
global using MudBlazor;
global using Cadenza.Domain.Enums;
global using Cadenza.Domain.Model;
global using Cadenza.Domain.Model.Artist;
global using Cadenza.Domain.Model.Album;
global using Cadenza.Domain.Model.Track;
global using Cadenza.Web.Core.Extensions;