global using Microsoft.AspNetCore.Components;
global using System.Web;
global using MudBlazor;
global using Cadenza.Domain.Enums;
global using Cadenza.Domain.Models;
global using Cadenza.Domain.Models.Artist;
global using Cadenza.Domain.Models.Album;
global using Cadenza.Domain.Models.Track;
global using Cadenza.Web.Core.Extensions;