trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: build
  displayName: 'Build'
  variables:
    projects: '**/*.csproj'
    buildPlatform: 'win-x64'
    buildConfiguration: 'Release'
  jobs:
  - job: build
    displayName: 'Build'

- stage: export
  displayName: 'Export to GitHub'
  variables:
  - group: github
  jobs:
  - job: export
    displayName: 'Export'
    steps:
    - task: CmdLine@1
      displayName: 'Set git user email'
      inputs:
        filename: git
        arguments: 'config --global user.email "$(github.email)"'
    - task: CmdLine@1
      displayName: 'Set git user name'
      inputs:
        filename: git
        arguments: 'config --global user.name "$(github.user)"'
    - task: CmdLine@1
      displayName: 'Pull from GitHub'
      inputs:
        filename: git
        arguments: 'pull $(github.repository.url) $(github.branch)'
    - task: CmdLine@1
      displayName: 'Pull Tags from GitHub'
      inputs:
        filename: git
        arguments: 'pull --tags $(github.repository.url.credentials)'
    - task: CmdLine@1
      displayName: 'Push to GitHub'
      inputs:
        filename: git
        arguments: 'push $(github.repository.url.credentials) head:$(github.branch)'
    - task: CmdLine@1
      displayName: 'Push Tags to GitHub'
      inputs:
        filename: git
        arguments: 'push --tags $(github.repository.url.credentials)'