parameters:
- name: projectFile
  type: string
- name: projectName
  type: string
- name: projectPath
  type: string
- name: isWebProject
  type: boolean
- name: artifactName
  type: string
- name: buildConfiguration
  type: string
  default: 'Release'
- name: buildPlatform
  type: string
  default: 'win-x64'
- name: outputPath
  type: string
  default: '$(Build.BinariesDirectory)/$(parameters.projectName)'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: $(parameters.projectFile)
    arguments: '--no-restore --configuration $(parameters.buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: $(parameters.isWebProject)
    projects: $(parameters.projectFile)
    arguments: '--no-build -c $(parameters.buildConfiguration) -r $(parameters.buildPlatform) --self-contained true -o $(parameters.outputPath)'
    zipAfterPublish: false
- task: FileTransform@2
  displayName: 'Transform App Settings'
  inputs:
    xmlTransformationRules: ''
    folderPath: '$(parameters.outputPath)/$(parameters.projectPath)'
    jsonTargetFiles: 'appsettings.json'
- publish: $(parameters.outputPath)
  displayName: 'Publish Artifact'
  artifact: '$(parameters.artifactName)-$(parameters.projectName)'