parameters:
- name: projectPath
  type: string
- name: serviceName
  type: string
- name: serviceDisplayName
  type: string
- name: artifactLocation
  type: string

steps:
- task: PowerShell@2
  displayName: 'Create Install File'
  inputs:
    targetType: 'inline'
    script: |
      Set-Content "${{ parameters.artifactLocation }}/installService.ps1" @"
      sc.exe create `"${{ parameters.serviceName }}`" start= delayed-auto binpath= `"`$(Get-Location)\${{ parameters.projectPath }}.exe`" displayname= `"${{ parameters.serviceDisplayName }}`"
      "@
- task: PowerShell@2
  displayName: 'Create Uninstall File'
  inputs:
    targetType: 'inline'
    script: |
      Set-Content "${{ parameters.artifactLocation }}/uninstallService.ps1" @"
      sc.exe delete `"${{ parameters.serviceName }}`"
      "@