trigger:
- main

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  
resources:
  repositories:
  - repository: self

variables:
  - group: azureSettings
  - name: 'Project'
    value: '**/Cadenza.Azure.Functions.csproj'
  - name: 'AppType'
    value: 'functionApp'

stages:
- stage: buildAndDeploy
  displayName: 'Build and Deploy'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        projects: '$(Project)'
        arguments: '--output publish_output --configuration Release'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'publish_output/'
        includeRootFolder: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

  - job: deployTest
    displayName: 'Deploy to Test'
    steps:
    - download: current
      artifact: drop
      patterns: '**/*.zip'
    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function App'
      inputs:
        azureSubscription: '$(TestSubscription)'
        appType: '$(AppType)'
        appName: '$(TestAppName)'
        package: '$(Pipeline.Workspace)\**\*.zip'
      
