trigger:
- main

pool:
  vmImage: windows-latest
  
resources:
  repositories:
  - repository: self

variables:
  artifactPrefix: 'drop' 
  
  syncService.projectName: 'LocalSyncService'
  syncService.projectFilePattern: '**/*Local.SyncService.csproj'
  syncService.projectPath: 'Cadenza.Local.SyncService'
  
  localApi.projectName: 'LocalAPI'
  localApi.projectFilePattern: '**/*Local.API.csproj'
  localApi.projectPath: 'Cadenza.Local.API'
  
  playerApi.projectName: 'PlayerAPI'
  playerApi.projectFilePattern: '**/Cadenza.API.csproj'
  playerApi.projectPath: 'Cadenza.API'
  
  app.projectName: 'Cadenza'
  app.projectFilePattern: '**/Cadenza.csproj'
  app.projectPath: 'Cadenza'

  syncService.serviceName: 'CadenzaSyncService'
  syncService.serviceDisplayName: 'Cadenza Sync Service'
  
  syncService.artifactName: '$(artifactPrefix)-$(syncService.projectPath)'
  syncService.artifactFolder: '$(Pipeline.Workspace)/$(syncService.artifactName)'
  syncService.artifactLocation: '$(syncService.artifactFolder)/$(syncService.projectPath)'
  syncService.archiveFile: '$(syncService.projectPath)-$(Build.BuildId).zip'

  localApi.artifactName: '$(artifactPrefix)-$(localApi.projectPath)'
  localApi.artifactFolder: '$(Pipeline.Workspace)/$(localApi.artifactName)'
  localApi.artifactLocation: '$(localApi.artifactFolder)/$(localApi.projectPath)'
  localApi.archiveFile: '$(localApi.projectPath)-$(Build.BuildId).zip'
  
  playerApi.artifactName: '$(artifactPrefix)-$(playerApi.projectPath)'
  playerApi.artifactFolder: '$(Pipeline.Workspace)/$(playerApi.artifactName)'
  playerApi.artifactLocation: '$(playerApi.artifactFolder)/$(playerApi.projectPath)'
  playerApi.archiveFile: '$(playerApi.projectPath)-$(Build.BuildId).zip'
  
  app.artifactName: '$(artifactPrefix)-$(app.projectPath)'
  app.artifactFolder: '$(Pipeline.Workspace)/$(app.artifactName)'
  app.artifactLocation: '$(app.artifactFolder)/$(app.projectPath)'
  app.archiveFile: '$(app.projectPath)-$(Build.BuildId).zip'

stages:
- stage: build
  displayName: 'Build'
  variables:
    - group: appSettings
    
  jobs:
  - job: buildSyncService
    displayName: 'Build Local Sync Service'
    steps:
    - template: Templates/build.yml@self
      parameters:
        projectFilePattern: $(syncService.projectFilePattern)
        projectPath: $(syncService.projectPath)
        artifactName: $(syncService.artifactName)
        isWebProject: false
  - job: buildLocalApi
    displayName: 'Build Local API'
    steps:
    - template: Templates/build.yml@self
      parameters:
        projectFilePattern: $(localApi.projectFilePattern)
        projectPath: $(localApi.projectPath)
        artifactName: $(localApi.artifactName)
        isWebProject: true
  - job: buildPlayerApi
    displayName: 'Build Player API'
    steps:
    - template: Templates/build.yml@self
      parameters:
        projectFilePattern: $(playerApi.projectFilePattern)
        projectPath: $(playerApi.projectPath)
        artifactName: $(playerApi.artifactName)
        isWebProject: true
  - job: buildWebApp
    displayName: 'Build Web App'
    steps:
    - template: Templates/build.yml@self
      parameters:
        projectFilePattern: $(app.projectFilePattern)
        projectPath: $(app.projectPath)
        artifactName: $(app.artifactName)
        isWebProject: true
        
- stage: test
  displayName: 'Test'
  jobs:
  - job: test
    displayName: 'Test'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration "Release"'

- stage: publish
  displayName: 'Publish'
  variables:
    syncService.name: 'CadenzaSyncService'
    syncService.displayName: 'Cadenza Sync Service'
  jobs:
  - job: publishSyncService
    displayName: 'Publish Local Sync Service'
    steps:
    - template: Templates/publish.yml@self
      parameters:
        projectName: $(syncService.projectName)
        projectPath: $(syncService.projectPath)
        serviceName: $(syncService.serviceName)
        serviceDisplayName: $(syncService.serviceDisplayName)
        artifactName: $(syncService.artifactName) 
        artifactLocation: $(syncService.artifactLocation)
        archiveFile: $(syncService.archiveFile)
  - job: publishLocalApi
    displayName: 'Publish Local API'
    steps:
    - template: Templates/publish.yml@self
      parameters:
        projectName: $(localApi.projectName)
        artifactName: $(localApi.artifactName) 
        artifactLocation: $(localApi.artifactLocation)
        archiveFile: $(localApi.archiveFile)
  - job: publishPlayerApi
    displayName: 'Publish Player API'
    steps:
    - template: Templates/publish.yml@self
      parameters:
        projectName: $(playerApi.projectName)
        artifactName: $(playerApi.artifactName) 
        artifactLocation: $(playerApi.artifactLocation)
        archiveFile: $(playerApi.archiveFile)
  - job: publishWebApp
    displayName: 'Publish Web App'
    steps:
    - template: Templates/publish.yml@self
      parameters:
        projectName: $(app.projectName)
        artifactName: $(app.artifactName) 
        artifactLocation: $(app.artifactLocation)
        archiveFile: $(app.archiveFile)
        
- stage: github
  displayName: 'GitHub'
  variables:
  - group: github
  jobs:
  - job: export
    displayName: 'Push to GitHub'
    steps:
    - template: Templates/github.yml@self